apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-mysql
  labels:
    name: simple-webapp-mysql
spec:
  serviceAccountName: clo835 
  containers:
  - name: simple-webapp-mysql
    image: 616865343531.dkr.ecr.us-east-1.amazonaws.com/final-group3:imgfrmconfigmap
    #image: 616865343531.dkr.ecr.us-east-1.amazonaws.com/final-group3:img-frm-url  #uncomment to generate imgane from hard coded url
       
    ports:
    - containerPort: 81
    env:
    - name: GROUP_NO
      valueFrom: 
        configMapKeyRef:
          name: webapp-config
          key: group
    # - name: S_Url
    #   valueFrom: 
    #     configMapKeyRef:
    #       name: webapp-config
    #       key: surl
    # - name: F_Url
    #   valueFrom: 
    #     configMapKeyRef:
    #       name: webapp-config
    #       key: furl
    volumeMounts:
    - name: app-secret-volumes
      mountPath: "/opt/app-secret-volumes"
      readOnly: true
    - name: config-volume
      mountPath: /clo835/config
    envFrom:
      - secretRef:
          name: app-secret
  volumes:
    - name: app-secret-volumes
      secret:
        secretName: app-secret
    - name: config-volume
      configMap:
        name: webapp-config
        items:
          - key: image_url
            path: image_url
  
