apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-mysql
  namespace: final
  labels:
    name : simple-webapp-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name : simple-webapp-mysql 
  
  template:  
    metadata:
      name: simple-webapp-mysql
      labels:
        name: simple-webapp-mysql
    spec:
      containers:
      - name: simple-webapp-mysql
        image: 308733176766.dkr.ecr.us-east-1.amazonaws.com/clo835:dockerv1.0
        ports:
        - containerPort: 81
        env:
        - name: Group_No
          valueFrom: 
            configMapKeyRef:
              name: webapp-config
              key: group
        - name: S_Url
          valueFrom: 
            configMapKeyRef:
              name: webapp-config
              key: surl
        - name: F_Url
          valueFrom: 
            configMapKeyRef:
              name: webapp-config
              key: furl
