name: push-toecr
on:



 push:
    branches: [ master ]



 workflow_dispatch:
  



jobs:

  build:
   
    name: Build Image
    runs-on: ubuntu-latest



   
    steps:
     
      - uses: actions/checkout@v3



    
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
       
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: us-east-1
          
      - name: Build, Test, Tag and push docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          ECR_REPOSITORY: final-group3
          IMAGE_TAG: imgv1.0
          
     
        run: |
          
          ls -ltra
         
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        
          docker run -d -p 8080:80 --name docker $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
         
          docker ps
          echo " sleep for 10 seconds "
          sleep 10
         
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
